# Understanding and Manipulating 2D Tensors with PyTorch

## Creating 2D tensors

In [1]:
import torch

twoD_list = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
twoD_tensor = torch.tensor(twoD_list)
print("The new 2D tensor:", twoD_tensor)

The new 2D tensor: tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])


### Exploring Tensor Attributes

In [2]:
print("The dimension of 2D tensor:", twoD_tensor.ndimension())
print("The shape of 2D tensor:", twoD_tensor.shape)
print("The size of 2D tensor:", twoD_tensor.size())
print("The number of elements:", twoD_tensor.numel())

The dimension of 2D tensor: 2
The shape of 2D tensor: torch.Size([3, 3])
The size of 2D tensor: torch.Size([3, 3])
The number of elements: 9


## Conversion Between Tensors and Other Data Structures

### Tensor to Numpy Array

In [4]:
twoD_numpy = twoD_tensor.numpy()
print("Tensor -> Numpy array:", twoD_numpy)

Tensor -> Numpy array: [[11 12 13]
 [21 22 23]
 [31 32 33]]


### Pandas DataFrame to Tensor

In [6]:
import pandas as pd

df = pd.DataFrame({'a': [11, 21, 31], 'b':[12, 22, 23]})
new_tensor = torch.from_numpy(df.values)
print("Tensor after conversion:", new_tensor)

Tensor after conversion: tensor([[11, 12],
        [21, 22],
        [31, 23]])


## Basic Tensor Operations

### Indexing and Slicing

In [8]:
tensor_example = torch.tensor([[11, 12, 13], [21, 22, 46], [31, 32, 33]])
print("The value of 2nd row 3rd col:", tensor_example[1, 2])

The value of 2nd row 3rd col: tensor(46)


## Tensor Arithmetic

### Addition

In [10]:
X = torch.tensor([[1, 0], [0, 1]])
Y = torch.tensor([[2, 1], [1, 2]])

X_plus_Y = X + Y

X_plus_Y

tensor([[3, 1],
        [1, 3]])

### Scalar Multiplication

In [11]:
two_Y = 2 * Y

two_Y

tensor([[4, 2],
        [2, 4]])

### Element-wise Product

In [12]:
X_times_Y = X * Y

X_times_Y

tensor([[2, 0],
        [0, 2]])

### Matrix Multiplication

In [13]:
A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])

A_times_B = torch.mm(A, B)
A_times_B

tensor([[0, 2],
        [0, 2]])